import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        Get started by &nbsp;
                        <code className={styles.code}>Minting NFT</code>
                    </p>
                    
                </div>

                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                    <div className={styles.thirteen}>
                        <Image
                            src="/thirteen.svg"
                            alt="13"
                            width={40}
                            height={31}
                            priority
                        />
                    </div>
                </div>

                <div className={styles.grid}>
                    <a
                        href="/NftPage"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Mint NFT <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Mint your own nft and start applying for&nbsp;loan.
                        </p>
                    </a>

                    <a
                        href="/applyLaonPage"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Apply loan <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Apply for loan here and get best rate&nbsp; and
                            security
                        </p>
                    </a>

                    <a
                        href="/lenderPage"
                        className={styles.card}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <h2 className={inter.className}>
                            Invest <span>-&gt;</span>
                        </h2>
                        <p className={inter.className}>
                            Give loans to people with total&nbsp;security.
                        </p>
                    </a>
                </div>
            </main>
        </>
    )
}
